### ISSUE TITLE
Slider - simplify

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars-careers#100]
Ellipsis 'more' functionality is janky

- [x] Multiple divs for the close buttons being created and not removed

<img width="1690" alt="Screenshot 2023-07-31 at 4 07 29 PM" src="https://github.com/hlxsites/caesars-careers/assets/7074782/636a2853-3dfd-4a04-99da-1b24c301d253">

- [x] In Mobile, after clicking more, the X close icon shows even after closing the overlay
- [x] In Mobile, they want to not have the more functionality and just show the entire description as it is today on the current site.
- [x] Simplify code as much as possible

**Comment by tmathern** [comment]
https://github.com/hlxsites/caesars-careers/pull/104/files for code simplifications that are not in the sliders.
